"""Edge auto-healing — Cloudflare Worker / Vercel Edge / WordPress patch generation."""
from __future__ import annotations

from urllib.parse import urlparse, parse_qsl

_EXPLICIT_FALLBACK_ERROR = "explicit fallback_url required — refusing to ship example.com default"

# Query keys forwarded from the incoming request to the fallback URL.
_PASSTHROUGH_KEYS = ("subid", "clickid", "btag")


def _js_escape(s: str) -> str:
    """Escape a string for safe interpolation inside single-quoted JS strings."""
    return (
        (s or "")
        .replace("\\", "\\\\")
        .replace("'", "\\'")
        .replace("\r", "\\r")
        .replace("\n", "\\n")
    )


def _src_path(source_url: str) -> tuple[str, str]:
    """Robust path extraction via urllib.parse.

    Returns (src_path, query_note). src_path is the origin path (default '/').
    Query strings are NOT part of path matching at the edge — the note records
    the accounted query so operators know path-only rules won't match on it.
    """
    try:
        parsed = urlparse(source_url or "")
        path = parsed.path or "/"
        note = ""
        if parsed.query:
            try:
                keys = [k for k, _ in parse_qsl(parsed.query, keep_blank_values=True)]
                note = f"source query accounted but not path-matched: ?{parsed.query} (keys: {', '.join(keys)})"
            except Exception:
                note = f"source query accounted but not path-matched: ?{parsed.query}"
        return path, note
    except Exception:
        return str(source_url or "/"), ""


def build_edge_patch(chain, fallback_url: str | None = None) -> dict:
    # No example.com default — caller must supply an explicit fallback URL.
    params_broken = chain.params_intact is False
    needs_patch = bool((not chain.chain_ok) or params_broken or (chain.final_status and chain.final_status >= 400))
    if fallback_url is None:
        # Refuse to ship a placeholder default; do NOT set chain.edge_patch.
        return {"needed": needs_patch, "error": _EXPLICIT_FALLBACK_ERROR}
    src_path, query_note = _src_path(getattr(chain, "source_url", "") or "")
    fb_esc = _js_escape(fallback_url)
    sp_esc = _js_escape(src_path)
    passthrough_list = ", ".join(f"'{k}'" for k in _PASSTHROUGH_KEYS)
    cf_worker = f"""// Auto-generated by iGaming-Redirect-Pathfinder — {_js_escape(getattr(chain, 'source_url', '') or '')}
// subid/clickid/btag passthrough: incoming affiliate query params are forwarded
// to the fallback URL via URLSearchParams so attribution survives the edge reroute.
addEventListener('fetch', event => {{ event.respondWith(handle(event.request)); }});
async function handle(req) {{
  const url = new URL(req.url);
  if (url.pathname === '{sp_esc}') {{
    const dest = new URL('{fb_esc}');
    for (const k of [{passthrough_list}]) {{
      const v = url.searchParams.get(k);
      if (v !== null && !dest.searchParams.has(k)) dest.searchParams.set(k, v);
    }}
    return Response.redirect(dest.toString(), 302);
  }}
  return fetch(req);
}}"""
    vercel_edge = f"""// middleware.js — auto-generated edge reroute
// subid/clickid/btag passthrough: incoming affiliate query params are forwarded
// to the fallback URL via URLSearchParams so attribution survives the edge reroute.
import {{ NextResponse }} from 'next/server';
export function middleware(req) {{
  if (req.nextUrl.pathname === '{sp_esc}') {{
    const dest = new URL('{fb_esc}');
    for (const k of [{passthrough_list}]) {{
      const v = req.nextUrl.searchParams.get(k);
      if (v !== null && !dest.searchParams.has(k)) dest.searchParams.set(k, v);
    }}
    return NextResponse.redirect(dest);
  }}
}}
export const config = {{ matcher: ['{sp_esc}'] }};"""
    wp_lines = [
        "# WP Redirection (auto-generated)",
        f"# Source: {getattr(chain, 'source_url', '')}",
        f"# Reason: {getattr(chain, 'broken_reason', '') or 'param-loss/broken-chain'}",
    ]
    if query_note:
        wp_lines.append(f"# NOTE: {query_note}")
    wp_lines.append(f"# subid/clickid/btag passthrough must be enabled (forward query params) so attribution survives.")
    wp_lines.append(f"Redirect 302 {src_path} {fallback_url}")
    wp_rule = "\n".join(wp_lines)
    patch = {"needed": True, "fallback_url": fallback_url, "cloudflare_worker_js": cf_worker,
             "vercel_edge_js": vercel_edge, "wordpress_redirect": wp_rule}
    if query_note:
        patch["src_query_note"] = query_note
    chain.edge_patch = patch
    return patch


def build_vendor_ticket(chain) -> str:
    stripped = [e.param for e in chain.param_events if e.status != "survived"]
    ticket = (f"Subject: Tracking failure on {chain.expected_operator} — {chain.geo} / {chain.device}\n\n"
              f"Hi {chain.expected_operator.title()} Affiliate Team,\n\n"
              f"Our monitor traced {chain.source_url}\n"
              f"Final URL: {chain.final_url} (HTTP {chain.final_status})\n"
              f"Chain length: {len(chain.hops)} hops, total latency {chain.latency.total_ms:.0f} ms\n"
              f"Stripped/mutated params: {', '.join(stripped) if stripped else 'none'}\n"
              f"Broken reason: {chain.broken_reason or 'n/a'}\n"
              f"Hops:\n" + "\n".join(f"  {h.index}. [{h.status}] {h.url} ({h.total_ms:.0f} ms)" for h in chain.hops) +
              f"\n\nPlease confirm tracking domain health and S2S fallback.\n\n— Publisher Affiliate Engineering")
    chain.vendor_ticket = ticket
    return ticket
